"""Add display_name

Revision ID: 850087bb9b22
Revises: 558bc48f530f
Create Date: 2026-01-29 03:51:21.850858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '850087bb9b22'
down_revision: Union[str, Sequence[str], None] = '558bc48f530f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imports', sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imports', 'display_name')
    # ### end Alembic commands ###
